var state = {
  profile: {},
  user: {},
  bearerToken: "",
  role: "", // artists, customers, organizer, service-provider
  roles: [],
  artist_types: null,
  genres: null,
  artists: null,
  plans: null,
  base_url: import.meta.env.BASE_URL,
  countries: null,
  cities: null,
  phone: null,
  account_type: "",
  account: null,
  isPhoneModify: false,
  custom_genre: "",
  artist_genre: [],
  proposal: {},
  selectedOption: "My Account",
  userId: "",
  cancelReasons: [
    "Sudden Scheduling Conflict",
    "Personal Emergency",
    "Health Issues",
    "Technical or Equipment Failure",
    "Conflict to previous commitment",
    "No Transportation",
    "Change of Mind",
  ],
  signupForm: {
    first_name: null,
    last_name: null,
    email: null,
    username: null,
    phone: null,
    password: null,
    password_confirmation: null,
    account_type: "customers",
    // account_type: '',
    phone: null,
    login_type: "email",
    verification_code: null,
  },
  phoneMask: "",
};

export default state;
